import type { Metadata } from "next";
import { Playfair_Display, Open_Sans } from "next/font/google";

import "./globals.css";

const playfairDisplay = Playfair_Display({
  display: "swap",
  weight: "variable",
  subsets: ["latin", "cyrillic"],
  variable: "--font-playfair-display",
});

const openSans = Open_Sans({
  display: "swap",
  weight: "variable",
  subsets: ["latin", "cyrillic"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
